### ISSUE TITLE
dealloc of SVPullToRefresh is not called

### ISSUE THREAD

**Issue by parvezq** [samvermette/SVPullToRefresh#43] opened 2012-07-17 06:40 UTC
If one converts the associated sample into a navigation based application with pushing of multiple SVViewController.xib by first adding a button in xib and then pushing the same view controller with tapping of that button. When we go back by tapping on the back button then the memory is not released back. This is probably due to the dealloc of both the view controller as well as SVPullToRefresh is not being called.
Also the latest version of SVPullToRefresh also gets crashed when the pull to refresh is in action and one goes back to previous view controller [pop action]

**Comment by samvermette** [comment] 2012-07-17 17:56
@parvezq it would help a ton if you could provide me with that demo project.

**Comment by parvezq** [comment] 2012-07-18 06:50
I think it is simple for you to do this. Just add a button in xib and in its touchup inside code in the view controller
again push the same view controller by using [alloc] initwithNibName] method. This way you can push several instances on
navigation stack. Then start going back by tapping on Back button on nav bar. This way you can see that dealloc of both
the view controller as well as the svpulltorefresh is not being called. Don't forget to first make the project navigation based
instead of view based. Also you can test this thing using instruments to see that allocations goes on rising
Thanks

**Comment by samvermette** [comment] 2012-07-18 13:48
@parvezq how are those instructions any simpler than sending me a link to download the project? The easier you make it for me, the more chances there are that I fix this issue quickly.

**Comment by parvezq** [comment] 2012-07-18 14:05
see attached sample project. The crash issue cannot be reproduced using this project but I have fixed that in another project like this

if (self.isObservingScrollView== NO) {
        return;
    }

in following methods of SVPullToRefresh class:
1. - (void)setScrollViewContentInset:(UIEdgeInsets)contentInset
2. - (UIEdgeInsets)originalScrollViewContentInset
3.- (void)observeValueForKeyPath:(NSString *)keyPath ofObject:(id)object change:(NSDictionary *)change context:(void *)context

That I have checked in a hurry and maybe I am wrong but you
should first look at the code and also give it a try in instruments

On 18-Jul-2012, at 7:18 PM, Sam Vermette wrote:

@parvezq how are those instructions any simpler than sending me a link to download the project? The easier you make it for me, the more chances there are that I fix this issue quickly.

---

**Comment by samvermette** [comment] 2012-07-19 04:31
@parvezq I don't see any attachment in your message. Try uploading a .zip of your project to something like DropBox or Cloud.app and paste the link here. I'm having a hard time trying to understand your "instructions". This would be a whole lot simpler if your demo project would clearly expose the 2 issues you're describing (dealloc not getting called and the crash when popping while it's still loading).

**Comment by parvezq** [comment] 2012-07-19 18:51
Sorry for the delay
I tried sending the sample project modified to show the dealloc not being called.
It is somehow not possible to produce the crash using this sample but you can look at another aspect of the problem which is growing memory allocations that you can see using instruments.
In my project where I am making use of this svpulltorefresh, the crash appears due to the pull to action still in progress while the controller itself is deallocated. I have already suggested fix for crash on the github issue section.
This time I have sent email with attached project, plz let me know if you receive it or not

Thanks
parvezq

**Comment by parvezq** [comment] 2012-07-20 05:48
sam
are you able to get that modified sample?

**Comment by samvermette** [comment] 2012-07-20 07:11
@parvezq I didn't get your email. What address did you send it to? Try hello@samvermette.com

**Comment by parvezq** [comment] 2012-07-27 05:49
are you able to see the issues that I have reported?

**Comment by samvermette** [comment] 2012-09-04 07:23
@parvezq actually this seems to be a duplicate of [Issue 53](https://github.com/samvermette/SVPullToRefresh/issues/53) (which should now be fixed).

**Closed as completed by samvermette** 2012-09-04 07:23 UTC

**Comment by parvezq** [comment] 2012-09-04 07:51
I have noticed the issue in your latest implementation as available on gitHub. The crash issue may be produced
by pulling the svpulltorefresh multiple times and suddenly press the back button so to move to previous screen.
In my case, The reason for crash is that SVPullToRefresh as part of stopping animation tries to update content offset of scrollView which is itself
deallocated.

Thanks
Parvez
On 04-Sep-2012, at 12:53 PM, Sam Vermette wrote:

@parvezqhttps://github.com/parvezq actually this seems to be a duplicate of Issue 53https://github.com/samvermette/SVPullToRefresh/issues/53 (which should now be fixed).

**Comment by samvermette** [comment] 2012-09-04 13:46
@parvezq do by "latest implementation" you mean the fix I pushed 6h ago?

**Comment by parvezq** [comment] 2012-09-05 04:58
Yes I pulled down the latest implementation a month ago which does contains the call to the method
[self stopObservingScrollView];
in dealloc.

Thanks
Pare
On 04-Sep-2012, at 7:17 PM, Sam Vermette wrote:

@parvezqhttps://github.com/parvezq do by "latest implementation" you mean the fix I pushed 6h ago?

**Comment by samvermette** [comment] 2012-09-05 07:34
@parvezq I pushed another fix about a day ago, try pulling that version and let me know if that solves it.
